### PR TITLE
Commiting further level 4 changes.

### PR DESCRIPTION
**Pull request by jayfriso**
Most of these changes are to level 4b but I've changed 4a-ii a bit too.
I have attached below a preview of the scene changes.
For 4a-ii ::
- made right vertical sawblades inverted
- changed size of ghost wall projector
  For 4b:
- A LOT of size changes. Realized this level was unnecessarily large.
- Changed the location of things and speed of things so the level is completable.

Also created a VerticalSawblade Inverted prefab which is a sawblade that fits more of the perspective if its at the right side of the screen.

scene 4a-i changes
4b scene changes

### CODE REVIEW

**Comment by jayfriso** [comment]
Also don't worry too much about the gate, because I've requested a level design change to Maia (you can see it [here](https://docs.google.com/presentation/d/1WSdoKKVyuxIUl99uT8gLkx_7Qm6if6pimR5Utt1UEP0/edit#slide=id.g142217ab2f_0_0) so that is just temporary.

**Comment by jayfriso** [comment]
Wait a bit, gonna add a little more changes Realized you can escape the right sawblades by going to the very right of it.

**Comment by jeaniewu** [comment]
There is already a tiny version of the ghostwall projector sprite

**Comment by jayfriso** [comment]
Yeah I know about the tiny ghostwall projector. I think that's a little too small, but the original projector was just WAAAY to huge so just shrinked it and scaled a bit.

**Comment by jeaniewu** [comment]
sure, good to go 👍

**Comment by Gowtham100** [comment]
looks good to me :+1:

**Pull request merged**
