### PR TITLE
Kyles new bug fixes

### PR DESCRIPTION
**Pull request by KyleSwensson**
Fixed jitter on wall bug by changing method of moving doll to rigidbody2d.moveposition from manually changing transform. deleted boundary check because jeanie said it wasn't being used anymore.

### CODE REVIEW

**Comment by jeaniewu** [comment]
looks good, I'm assuming the player collider still works against items that don't have rigidbody in them?

**Comment by KyleSwensson** [comment]
Yeah, collider still interacts normally with everything. When you move somethings rigidbody I'm pretty sure its transform automatically follows it.

**Comment by KyleSwensson** [comment]
also can someone +1 me again :L I deleted an extra wall in 4a-i i just wanna make sure it's okay to edit scenes and im not gonna break stuff

**Comment by Gowtham100** [comment]
:+1:

**Pull request merged**
