### PR TITLE
Jays ui fixing

### PR DESCRIPTION
**Pull request by jayfriso**
As I don't want to block any progress, commiting UI changes for level Open Scene - 5b.
- Made UI Scale to screen size
- Fixed Text to scale on size.
- Made all camera distances 8
- Set the camera borders to be more consistent

### CODE REVIEW

**Comment by jayfriso** [comment]
Oh yeah, also changed up some of the secret items (level 4 and level 5 were way to small and hard to find... I just realized they existed now).

**Comment by jayfriso** [comment]
Also commit 100 woooooooooooooooooooooooo

**Comment by Gowtham100** [comment]
no codes so im good with it :+1:

**Comment by jeaniewu** [comment]
yep same here :+1:

**Comment by jeaniewu** [comment]
but the point of secret item is to make it hard to find

**Comment by jeaniewu** [comment]
also @jayfriso I hope you have tested that all the scenes run?

**Pull request merged**
