### PR TITLE
fix ghostwall prefab and fix ghost selection

### PR DESCRIPTION
**Pull request by jeaniewu**
Now you can possess closet doll first, please play around with the ghost selection

### CODE REVIEW

**Comment by jeaniewu** [comment]
@jayfriso review?

**Comment by jayfriso** [comment]
Looks good to merge but one thing I would consider doing if you have the time is to maybe move the switching logic out of the level manager and into some kind of switch controller script as switching doesn't really have anything to do with "managing the level". 

It's up to you for this change though as I don't know the details of the level manager script that well.

**Comment by Gowtham100** [comment]
:+1: also agree with Jay wouldnt it be better?

**Comment by jeaniewu** [comment]
will update it in another review, for now it seems that it's good to go

**Pull request merged**
