### PR TITLE
Commiting end credits scene.

### PR DESCRIPTION
**Pull request by jayfriso**
Shows  the logo, credits, and the agda logo scrolling upwards, then fades out and opens the title screen.
You can also press "z" to speed up the scrolling.

NOTE: You may notice that the background and the credits text sprites aren't compressed to 1080px. This is because it looks pretty pixalated and bad when we do this, as the credits sprite especially is zoomed in quite a lot.

### CODE REVIEW

**Comment by jayfriso** [comment]
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
I forgot to modify the final scene script to include the transition to the credits scene. As Jeanie's pull request has some changes to the script, Ill change that after that gets merged in.

So if you can don't merge this in yet.

**Comment by jeaniewu** [comment]
lol ur not getting +1, chill

**Comment by jayfriso** [comment]
Ok fixed now, should be good to merge.

**Comment by jayfriso** [comment]
Also I disabled both the spazzing sound and the music box sound at the end for now cause I thought it sounded a bit out of place and annoying. We can enable it back if we think we want them again.

**Pull request merged**
